{
    'name': 'auren_astore',
    'version': '18.1.8',
    'depends': [
        'base',
        'sale',
        'sale_management',
        'account',
        'account_accountant',
        'stock',
        'crm',
        'board',
        'journal_warehouse',
    ],
    'category': 'Category',
    'description': "aStore",
    'website': '',
    'installable': True,
    'application': True,
    'auto_install': False,
    'data': [
        'views/aurb_astore_pos.xml',
        'views/aurb_astore_sale_order_views.xml',
        'views/aurb_astore_stock_picking_views.xml',
        'views/aurb_astore_move_pos_views.xml',
        'views/aurb_astore_res_user.xml',
        'views/aurb_astore_payments_category_pos_views.xml',
        'views/aurb_astore_payments_pos_views.xml',
        'views/aurb_astore_close_pos.xml',
        'views/aurb_astore_account_move_views.xml',
        'views/aurb_astore_payment_register_views.xml',
        'views/aurb_astore_res_config_settings_views.xml',
        'views/aurb_astore_method_payment_views.xml',
        'views/aurb_astore_pos_payment_method_views.xml',
        'views/aurb_astore_partners_views.xml',
        'views/aurb_astore_products_views.xml',
        'report/aurb_astore_reporting_pos.xml',
        'wizard/aurb_astore_archived_closed_move_views.xml',
        'security/astore_security.xml',
        'security/group_security.xml',
        'security/ir.model.access.csv',
        'views/astore_menu.xml',
        'views/dashboard.xml'

    ],
    "assets": {
        "web.assets_backend": [
            "astore/static/src/*",
        ],
    },
    'license': 'LGPL-3',
}
