{
    'name': 'extended_uom',
    'version': '18.1.2',
    'depends': [
        'base',
        'sale',
        'purchase',
        'sale_management',
        'stock',
        'delivery',
    ],
    'category': 'Category',
    'description': "Modulo de unidad de medida ampliada",
    'website': '',
    'installable': True,
    'application': True,
    'auto_install': False,
    'data': [
        'security/ir.model.access.csv',
        'security/extended_uom_group_security.xml',
        'views/auren_exuom_product_template.xml',
        'views/auren_exuom_product_uom_purchase.xml',
        'views/auren_exuom_product_uom_sale.xml',
        'views/auren_exuom_product_uom_scandal.xml',
        'views/auren_exuom_purchase_order.xml',
        'views/auren_exuom_sale_order.xml',
        'views/auren_exuom_res_config_settings_views.xml',
    ],
    'license': 'LGPL-3',
}
