{
    'name': 'reporting',
    'version': '18.1.2',
    'depends': [
        'base',
        'crm',
        'sale',
        'account',
        'account_accountant',
        'stock',
    ],
    'category': 'Category',
    'description': "Reporting",
    'website': '',
    'installable': True,
    'application': True,
    'auto_install': False,
    'data': [
        'report/report_base.xml',
        'report/sale_order_with_out_disc.xml',
        'report/sale_order_report_with_out_disc.xml',
        'report/sale_order.xml',
        'report/sale_order_report.xml',
        'report/stock_picking.xml',
        'report/stock_picking_report.xml',
        'report/account_move.xml',
        'report/account_move_report.xml',
        'views/aurb_rep_res_company.xml',
        'views/aurb_rep_sale_order.xml',
        'views/aurb_rep_stock_move.xml',
        'views/aurb_rep_account_move.xml',
        'views/aurb_rep_format.xml',
        'security/ir.model.access.csv',
    ],
    'license': 'LGPL-3',
}
