{
    'name': 'historical_data_transferred',
    'version': '17.1.1',
    'depends': ['base'],
    'category': 'Category',
    'description': "Historical data Transferred",
    'website': '',
    'installable': True,
    'application': True,
    'auto_install': False,
    'css': ['static/src/css/aurb_hdt_invoice_style.css',],
    'data': [
        'views/company_views.xml',
        'views/country_views.xml',
        'views/country_ce_views.xml',
        'views/warehouse_views.xml',
        'views/warehouse_currency_views.xml',
        'views/warehouse_pricelist_views.xml',
        'views/warehouse_location_views.xml',
        'views/vehicle_views.xml',
        'views/subaccounts_views.xml',
        'views/currency_views.xml',
        'views/currency_subaccount_views.xml',
        'views/currency_change_views.xml',
        'views/seller_views.xml',
        'views/seller_cumulative_views.xml',
        'views/seller_commission_views.xml',
        'views/partners_views.xml',
        'views/partners_cards_views.xml',
        'views/partners_risk_views.xml',
        'views/partners_payment_terms_views.xml',
        'views/partners_account_views.xml',
        'views/partners_contact_views.xml',
        'views/partners_comments_views.xml',
        'views/partners_address_views.xml',
        'views/partners_manual_views.xml',
        'views/items_views.xml',
        'views/items_desc_views.xml',
        'views/items_price_views.xml',
        'views/items_batch_views.xml',
        'views/items_batch_piece_views.xml',
        'views/items_batch_incident_views.xml',
        'views/bank_views.xml',
        'views/bank01_views.xml',
        'views/bank_entity_views.xml',
        'views/bank_office_views.xml',
        'views/transport_agency_views.xml',
        'views/delivery_zone_views.xml',
        'views/exercices_views.xml',
        'views/company_parameters_views.xml',
        'views/compuser_parameters_views.xml',
        'views/categories_views.xml',
        'views/languages_views.xml',
        'views/keys_views.xml',
        'views/document_views.xml',
        'views/document_total_views.xml',
        'views/document_tax_views.xml',
        'views/order_views.xml',
        'views/order_lines_views.xml',
        'views/order_manual_desc_views.xml',
        'views/document_notes_views.xml',
        'views/order_notes_lines_views.xml',
        'views/order_manual_measures_views.xml',
        'views/delivery_views.xml',
        'views/delivery_lines_views.xml',
        'views/invoice_views.xml',
        'views/stock_transfer_views.xml',
        'views/stock_transfer_lines_views.xml',
        'views/manufacturing_orders_views.xml',
        'views/manufacturing_orders_lines_views.xml',
        'views/stock_movements.xml',
        'views/order_relationship_views.xml',
        'views/order_to_notify_views.xml',
        'views/order_preparation_status_views.xml',
        'views/pos_views.xml',
        'views/pos_payment_method_views.xml',
        'views/pos_account_payment_method_views.xml',
        'views/pos_assignment_views.xml',
        'views/pos_payment_method_by_pos_views.xml',
        'views/pos_documents_views.xml',
        'views/pos_collections_views.xml',
        'views/pos_cumulative_views.xml',
        'views/pos_cash_count_views.xml',
        'views/default_printer_views.xml',
        'views/incoming_payments_views.xml',
        'views/incoming_payments_traceability_views.xml',
        'views/incoming_payments_effect_views.xml',
        'views/incoming_payments_original_views.xml',
        'views/outcoming_payments_views.xml',
        'views/outcoming_payments_traceability_views.xml',
        'views/outcoming_payments_effect_views.xml',
        'views/outcoming_payments_tpv_views.xml',
        'views/accounting_entries_views.xml',
        'report/aurb_hdt_reporting.xml',
        'security/auren_hdt_security.xml',
        'security/ir.model.access.csv',
        'views/historical_menus.xml',
        'report/aurb_hdt_invoice_prueba.xml',
        'report/aurb_hdt_layout_footer.xml',
        'report/aurb_hdt.xml',

    ],
    'license': 'LGPL-3',
}
