{
    'name': 'auren_otools',
    'version': '18.1.1',
    'depends': [
        'base',
        'sale',
        'purchase',
        'sale_management',
        'account',
        'account_accountant',
        'stock',
        'delivery',
        'crm',

    ],
    'category': 'Category',
    'description': "Auren Otools",
    'website': '',
    'installable': True,
    'application': True,
    'auto_install': False,
    'data': [
        'security/auren_otools_security.xml',
        'security/auren_otools_group_security.xml',
        'security/ir.model.access.csv',
        'report/aurb_sale_picking_report_action.xml',
        'report/aurb_sale_picking_report.xml',
        'views/aurb_cm_location.xml',
        'views/aurb_cm_sale_order.xml',
        'views/aurb_cm_purchase_order.xml',
        'views/aurb_cm_product_template.xml',
        'views/aurb_cm_product_uom_sale.xml',
        'views/aurb_cm_product_uom_purchase.xml',
        'views/aurb_cm_res_partner.xml',
        'views/auren_sales_res_partners_view.xml',
        'views/auren_sales_sale_order_view.xml',
        'views/aurb_sale_picking.xml',
        'views/aurb_sale_order_line_tree.xml',
        'views/aurb_prod_product_category.xml',
        'views/aurb_cm_res_config_settings_views.xml',
        'views/aurb_cm_cost_standard.xml',
        'views/cm_menu.xml',
    ],
    'license': 'LGPL-3',
}
