{
    'name': "suconspa_adapt",
    'version': '18.1.5',
    'depends': ['base',
                'sale',
                'sale_management',
                'account_batch_payment',
                ],
    'category': 'Category',
    'description': "Módulo de adaptaciones para Suconspa",
    'website': 'https://www.suconspa.es/',
    'installable': True,
    'application': True,
    'auto_install': False,
    'data': [
        'security/ir.model.access.csv',
        'views/suco_sale_order_view.xml',
        'views/suco_purchase_order_view.xml',
        'views/suco_account_batch_payment_view.xml',
        'report/suco_report_base.xml',
        'report/suco_sale_order_with_out_disc.xml',
        'report/suco_sale_order_report_with_out_disc.xml',
        'report/suco_sale_order.xml',
        'report/suco_sale_order_report.xml',
        'report/suco_stock_picking.xml',
        'report/suco_stock_picking_report.xml',
        'report/suco_account_move.xml',
        'report/suco_account_move_report.xml',
    ],
    'license': 'LGPL-3',
}
