{
    'name': "Personalizaciones Pedret",
    'version': '17.1.13',
    'depends': ['base',
                'account',
                'account_accountant',
                'sale', 'sale_management',],
    'category': 'Category',
    'description': "Modulo pedret",
    'website': 'https://auren.com/es/',
    'installable': True,
    'application': True,
    'auto_install': False,
    'data': [
        'security/ir.model.access.csv',

        'report/aurb_sale_picking_report_action.xml',
        'report/aurb_sale_picking_report.xml',
        'report/aurb_sale_picking_report2_action.xml',
        'report/aurb_sale_picking_report2.xml',
        'report/aurb_sale_picking_report3_action.xml',
        'report/aurb_sale_picking_report3.xml',
        'report/pedr_report_base.xml',
        'report/pedr_account_move.xml',
        'report/pedr_account_move_report.xml',
        'report/pedr_sale_order.xml',
        'report/pedr_sale_order_report.xml',
        'report/pedr_sale_order_with_out_disc.xml',
        'report/pedr_sale_order_report_with_out_disc.xml',
        'report/pedr_stock_picking.xml',
        'report/pedr_stock_picking_report.xml',
        'views/aurb_sale_order_line_tree.xml',
        'views/aurb_sale_picking.xml',
        'views/pedret_sale_order_form.xml',
        'views/aurb_cm_sale_order.xml',
        'views/aurb_pedret_product_princelist_item.xml',
        'views/aurb_cm_account_move.xml',
        'views/aurb_pedret_purchase_requisition_view.xml',
        'views/pedret_purchase_order_view.xml',
    ],
    'license': 'LGPL-3',
}
