{
    'name': "Adaptaciones_Fedor",
    'version': '17.1.33',
    'depends': ['base', 'product', 'sale', 'partner_commission', 'stock'],
    'category': 'Category',
    'description': "Módulo de adaptaciones para FEdor",
    'website': 'http://www.fedorsa.com',
    'installable': True,
    'application': True,
    'auto_install': False,
    'data': [
        'security/ir.model.access.csv',
        'views/fedor_product_template_form.xml',
        'views/fedor_product_template list.xml',
        'views/fedor_product_family.xml',
        'views/fedor_type.xml',
        'views/fedor_log_export_import.xml',
        'views/fedor_log_export_import_line.xml',
        'views/fedor_export_cron.xml',
        'views/fedor_account_payment_term_form.xml',
        'views/fedor_product_pricelist_form.xml',
        'views/fedor_res_partner.xml',
        'views/fedor_account_move_form.xml',
        'views/fedor_stock_picking_form.xml',
        'wizard/fedor_import_order.xml',
        'views/fedor_menu.xml',
    ],
    'license': 'LGPL-3',
}
